# Generated by Django 5.2.4 on 2025-07-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devhubapp', '0002_administrator_address_administrator_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
